from fastapi import APIRouter, Depends, status, HTTPException
from typing import List, Dict, Any
from datetime import datetime

from app.core.security import get_current_government_user
from app.core.database import get_database
from app.models.analytics import MonthlyUserAnalytics

router = APIRouter()


@router.get("/user-analytics", status_code=status.HTTP_200_OK, response_model=List[MonthlyUserAnalytics])
async def get_user_analytics(
    current_admin_id: str = Depends(get_current_government_user),
    year: int = None
) -> List[MonthlyUserAnalytics]:
    """
    Get monthly user analytics including actual and predicted data.
    
    This endpoint returns user growth analytics with both historical (actual) data
    and AI-predicted future user counts generated by Prophet model.
    
    Args:
        year: Optional year filter. If not provided, returns all data.
        
    Returns:
        List of monthly analytics with actual and predicted user counts
    """
    db = get_database()
    
    try:
        # Build query
        query = {}
        if year:
            query["year"] = year
        
        # Fetch analytics from database
        analytics_cursor = db.monthly_user_analytics.find(query).sort([("year", 1), ("month_number", 1)])
        analytics_list = await analytics_cursor.to_list(length=None)
        
        if not analytics_list:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No analytics data found. Please run the analytics pipeline first."
            )
        
        # Convert to response model
        result = []
        for item in analytics_list:
            result.append(MonthlyUserAnalytics(
                month_number=item["month_number"],
                year=item["year"],
                actual_data=item.get("actual_data") or 0,
                predicted_data=item.get("predicted_data") or 0,
                predicted_at=item["predicted_at"]
            ))
        
        return result
        
    except HTTPException:
        raise
    except Exception as e:
        print(f"Error fetching user analytics: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch analytics: {str(e)}"
        )


@router.get("/user-analytics/summary", status_code=status.HTTP_200_OK)
async def get_analytics_summary(
    current_admin_id: str = Depends(get_current_government_user)
) -> Dict[str, Any]:
    """
    Get summary statistics of user analytics.
    
    Returns:
        Summary with total users, growth rate, and prediction accuracy
    """
    db = get_database()
    
    try:
        # Get latest analytics
        latest_actual = await db.monthly_user_analytics.find_one(
            {"actual_data": {"$ne": None}},
            sort=[("year", -1), ("month_number", -1)]
        )
        
        # Get next month prediction
        current_date = datetime.utcnow()
        next_month_prediction = await db.monthly_user_analytics.find_one({
            "year": current_date.year,
            "month_number": current_date.month + 1 if current_date.month < 12 else 1,
            "actual_data": None
        })
        
        # Calculate total users from actual data
        pipeline = [
            {"$match": {"actual_data": {"$ne": None}}},
            {"$group": {"_id": None, "total": {"$sum": "$actual_data"}}}
        ]
        total_cursor = db.monthly_user_analytics.aggregate(pipeline)
        total_result = await total_cursor.to_list(length=1)
        total_users = total_result[0]["total"] if total_result else 0
        
        return {
            "total_users": total_users,
            "latest_month_users": latest_actual.get("actual_data") if latest_actual else 0,
            "latest_month": latest_actual.get("month_number") if latest_actual else None,
            "latest_year": latest_actual.get("year") if latest_actual else None,
            "next_month_prediction": next_month_prediction.get("predicted_data") if next_month_prediction else None,
            "data_last_updated": latest_actual.get("predicted_at") if latest_actual else None
        }
        
    except Exception as e:
        print(f"Error fetching analytics summary: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch summary: {str(e)}"
        )


@router.get("/service-ratings", status_code=status.HTTP_200_OK)
async def get_service_ratings_distribution(
    current_admin_id: str = Depends(get_current_government_user)
) -> Dict[str, Any]:
    """
    Get service ratings distribution categorized into three ranges.
    
    Returns:
        Distribution of services by rating: under 2, between 2-4, and 4-5
    """
    db = get_database()
    
    try:
        # Count services in each rating range
        under_2 = await db.services.count_documents({"rating": {"$lt": 2}})
        between_2_4 = await db.services.count_documents({"rating": {"$gte": 2, "$lt": 4}})
        above_4 = await db.services.count_documents({"rating": {"$gte": 4}})
        
        return {
            "under_2": under_2,
            "between_2_4": between_2_4,
            "above_4": above_4,
            "total": under_2 + between_2_4 + above_4
        }
        
    except Exception as e:
        print(f"Error fetching service ratings: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch service ratings: {str(e)}"
        )
